#!/bin/bash

# call with --verbose for increased output

USERNAME="REPLACE WITH YOUR J5 SERVER USERNAME"
PASSWORD="REPLACE WITH YOUR J5 SERVER PASSWORD"
J5URL="http://j5.jbei.org/bin/j5_xml_rpc.pl"

# maximum number of generations
GEN=10
# initial number of tweaks (modifications within the design constraints) per design
TWEAKS=50
# maximum population size
POP=50
# number of childern generated per parent in a round of evolution
MULT=3

# Copyright ©2013. The Regents of the University of California (Regents). All
# Rights Reserved. Permission to use, copy, modify, and distribute this
# software and its documentation for educational, research, and
# not-for-profit purposes, without fee and without a signed licensing
# agreement, is hereby granted, provided that the above copyright notice,
# this paragraph and the following two paragraphs appear in all copies,
# modifications, and distributions. Contact The Office of Technology
# Licensing, UC Berkeley, 2150 Shattuck Avenue, Suite 510, Berkeley, CA
# 94720-1620, (510) 643-7201, for commercial licensing opportunities.
# 
# Created by William J. Holtz, The California Institute for Quantitative
# Biosciences, University of California, Berkeley.
# 
# IN NO EVENT SHALL REGENTS BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT,
# SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS,
# ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF
# REGENTS HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# REGENTS SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE.  THE SOFTWARE AND ACCOMPANYING DOCUMENTATION, IF ANY, PROVIDED
# HEREUNDER IS PROVIDED "AS IS". REGENTS HAS NO OBLIGATION TO PROVIDE
# MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

OUT="DE_`date +%Y%m%d_%H%M%S`_$$"
FULLOUTDIR=$(readlink -m ./$OUT)

mkdir $FULLOUTDIR
echo "outputing to directory $FULLOUTDIR"
echo "running designEvolver.py --username=$USERNAME --password=$PASSWORD--j5URL=$J5URL --param=j5parameters.csv --seq=mastersequences.csv --zip=masterzippedsequences.zip  --parts=partslist.csv --order=targetpartsorder.csv --eugene=eugeneruleslist.eug --plasmid=j5_plasmids.csv --oligo=j5_oligos.csv --direct=j5_directsyntheses.csv --outdir=$FULLOUTDIR --numgen=$GEN --maxpop=$POP --tweaks=$TWEAKS --multiplier=$MULT $*" > $FULLOUTDIR/DE.log
designEvolver.py --username=$USERNAME --password=$PASSWORD --j5URL=$J5URL --param=j5parameters.csv --seq=mastersequences.csv --zip=masterzippedsequences.zip  --parts=partslist.csv --order=targetpartsorder.csv --eugene=eugeneruleslist.eug --plasmid=j5_plasmids.csv --oligo=j5_oligos.csv --direct=j5_directsyntheses.csv --outdir=$FULLOUTDIR --numgen=$GEN --maxpop=$POP --tweaks=$TWEAKS --multiplier=$MULT $* >> $FULLOUTDIR/DE.log

